server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/tdubbo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    druid:
      max-active: 30 #最大连接数
      min-idle: 5 #最小连接数
      max-wait: 60000 #最大等待时间
      initial-size: 5 #初始化时建立物理连接数
      time-between-eviction-runs-millis: 60000  #多久一次检查空连接
      validation-query: SELECT 1 FROM DUAL  # 测试sql连接
      filters: stat,wall  #监听
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500  #开启慢查询
  redis:
    cluster:  # 配置集群节点
      nodes: 192.168.17.17:7001,192.168.17.17:7002,192.168.17.17:7003
    password: 1qaz2wsx  #集群密码
    timeout: 5000 #超时时间
    lettuce:
      pool:
        max-wait: -1 #连接最大等待时间
        max-active: 8 #连接池最大数量
        max-idle: 8 #最大空闲连接诶
        min-idle: 0 #最小空闲连接
    database: 0

dubbo:
  application:
    name: tdubbo-provider
  registry:
    address: 192.168.17.17:2181,192.168.17.18:2181,192.168.17.19:2181,192.168.17.20:2181
    protocol: zookeeper
